# Generated by Django 5.2.12 on 2026-04-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Atelier Habitat', max_length=120)),
                ('tagline', models.CharField(default='Interior stories, furniture curation, and spatial elegance.', max_length=200)),
                ('hero_title', models.CharField(default='Curated interiors for modern living', max_length=200)),
                ('hero_subtitle', models.TextField(default='A premium editorial platform blending interior design insights, furniture selections, and portfolio-driven storytelling for discerning homeowners and boutique hospitality brands.')),
                ('about_text', models.TextField(default='Atelier Habitat is a Dhaka-rooted interior design editorial brand focused on warm minimalism, layered textures, and functional luxury across residential and boutique commercial spaces.')),
                ('contact_email', models.EmailField(default='hello@atelierhabitat.com', max_length=254)),
                ('phone', models.CharField(default='+880 1700-000000', max_length=50)),
                ('address', models.CharField(default='Gulshan Avenue, Dhaka, Bangladesh', max_length=255)),
                ('map_embed', models.TextField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('meta_description', models.CharField(default='Luxury interior design and furniture blog with portfolio case studies and contact-ready lead generation.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
