# Generated by Django 5.2.12 on 2026-04-03 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('subtitle', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('material', models.CharField(max_length=150)),
                ('dimensions', models.CharField(max_length=150)),
                ('price_label', models.CharField(default='Custom Quote', max_length=80)),
                ('cover_image', models.ImageField(upload_to='furniture/')),
                ('gallery_image', models.ImageField(blank=True, upload_to='furniture/gallery/')),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='furniture.furniturecategory')),
            ],
        ),
    ]
