# Generated by Django 5.2.12 on 2026-04-03 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('client', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('scope', models.CharField(max_length=150)),
                ('summary', models.TextField()),
                ('challenge', models.TextField()),
                ('solution', models.TextField()),
                ('result', models.TextField()),
                ('cover_image', models.ImageField(upload_to='portfolio/')),
                ('completed_on', models.DateField()),
                ('published', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/')),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.portfolioproject')),
            ],
        ),
    ]
